engines:
  eslint:
    enabled: true

ratings:
  paths:
    - bin/**
    - src/**
    - test/**

# You can globally exclude files from being analyzed by any engine using the
# exclude_paths key.

# exclude_paths:
#- spec/**/*
#- vendor/**/*
