language: node_js

node_js:
  - "4.4.3"
  - "5.11.0"

sudo: false

cache:
  directories:
    - node_modules

before_script:
  - npm run ci

after_script:
  - $(npm bin)/coveralls < ./coverage/lcov.info
