language: node_js

node_js:
  - "0.12"
  - "4.0.0"
  - "io.js"

sudo: false

cache:
  directories:
    - node_modules

before_script:
  - npm run ci

after_script:
  - $(npm bin)/coveralls < ./coverage/lcov.info
